### ISSUE TITLE
   ErrorException    mkdir(): Invalid argument While Creating CRUD from terminal

### ISSUE THREAD

**Issue by stitpragya22** [misterdebug/crud-generator-laravel#16]
php artisan make:crud post1 "title:string, content:text"
Created Controller: Post1s
Created views directory: post1s
Created View: index.blade.php
Created View: create.blade.php
Created View: show.blade.php
Created View: edit.blade.php

   ErrorException

  mkdir(): Invalid argument

  at C:\laragon\www\example-app\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:631
    627▕         if ($force) {
    628▕             return @mkdir($path, $mode, $recursive);
    629▕         }
    630▕
  ➜ 631▕         return mkdir($path, $mode, $recursive);
    632▕     }
    633▕
    634▕     /**
    635▕      * Move a directory.

  1   C:\laragon\www\example-app\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:631
      mkdir("")

  2   C:\laragon\www\example-app\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:338
      Illuminate\Filesystem\Filesystem::makeDirectory()

**Comment by stitpragya22** [comment]
I think it's near to Model creation. BUt not know how to solve it.

**Comment by stitpragya22** [comment]
Something near here 

 /* *************************************************************************

                                        MODEL

        ************************************************************************* */

        if(!File::exists($this->pathsAndNamespacesService->getRealpathBaseModel()))
            File::makeDirectory($this->pathsAndNamespacesService->getRealpathBaseModel());

        // we create our model
        $this->createRelationships([], $namingConvention);

**Comment by misterdebug** [comment]
Hi @stitpragya22, do you have your requests directory already created? If not, create it and it will be okay :)
Or check this : https://github.com/misterdebug/crud-generator-laravel/pull/13

**Comment by misterdebug** [comment]
fixed thanks to @hlombroso

**Comment by stitpragya22** [comment]
thank you for reply but I not get what is problem. does it is solved ? and which directory should I create it creates views folder , and I think Controler and Models are in existing folders only. kindly explain , thanks.

**Comment by misterdebug** [comment]
Just update the package and it'll be okay :)

**Comment by stitpragya22** [comment]
thank you very much..
