### ISSUE TITLE
Creation model Post faild with error exeption

### ISSUE THREAD

**Issue by YounessTayer** [misterdebug/crud-generator-laravel#18]
Do you want to create relationships between this model and an other one? (yes/no) [no]:
 > no

Created Migration: 2023_03_13_012707_create_post_tag_table.php

   Illuminate\Contracts\Filesystem\FileNotFoundException 

  File does not exist at path MyAppPath/vendor/mrdebug/crudgen/src/Services/../stubs/Model.stub.

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:59
     55▕         if ($this->isFile($path)) {
     56▕             return $lock ? $this->sharedGet($path) : file_get_contents($path);
     57▕         }
     58▕ 
  ➜  59▕         throw new FileNotFoundException("File does not exist at path {$path}.");
     60▕     }
     61▕ 
     62▕     /**
     63▕      * Get contents of a file with shared access.

      +22 vendor frames 
  23  artisan:37
      Illuminate\

**Comment by misterdebug** [comment]
Oops, in quick fix you can rename `src/stubs/model.stub` to `Model.stub`
I will fix it asap

Thx for you issue :)

**Comment by YounessTayer** [comment]
Hi,
Worked, thank you.👍

Le lun. 13 mars 2023 à 07:54, MisterDebug ***@***.***> a
écrit :

**Comment by misterdebug** [comment]
Perfect :)
