### ISSUE TITLE
Wishlist: Base path

### ISSUE THREAD

**Issue by baradhili** [misterdebug/crud-generator-laravel#22]
for example, it would be nice to be able to set the crud up in admin.crud instead of crud

**Comment by misterdebug** [comment]
It's planned and with custom paths for each directory (not only views) but I need to think how to handle the deletion with rm:crud command

**Comment by misterdebug** [comment]
I've opened a discussion/poll about it here : https://github.com/misterdebug/crud-generator-laravel/discussions/30
I close this issue
