### ISSUE TITLE
Wishlist: relationships generate select controls

### ISSUE THREAD

**Issue by baradhili** [misterdebug/crud-generator-laravel#25]
So that the CRUD is pretty usable out of the box

**Comment by misterdebug** [comment]
You're talking about which type of select controls? Can you give me an example? Thx

**Comment by baradhili** [comment]
So if you login to http://demo-freelancer-crm.quickadminpanel.com/ and then visit http://demo-freelancer-crm.quickadminpanel.com/admin/projects/create you will notice the select control letting you link a project to a client

**Comment by misterdebug** [comment]
select2 is js ahah
